---
 - name: create a docker container
   docker_container:
      name: mysql
      image: mysql:8.0
      ports:
       - "3306:3306"
      env:
         MYSQL_ROOT_PASSWORD: '{{ wp_root_password }}'
         MYSQL_USER: '{{ wp_db_user }}'
         MYSQL_PASSWORD: '{{ wp_db_password }}'
         MYSQL_DATABASE: '{{ wp_db_name }}'
